# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ragflow_register_login_getapi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#ragflow_register_login_getapi.proto\x12\x07ragflow"\x1f\n\x0eResponseString\x12\r\n\x05reply\x18\x01 \x01(\t"n\n\x17RegistrationCredentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\x12\x65ncrypted_password\x18\x03 \x01(\t\x12\r\n\x05nonce\x18\x04 \x01(\t\x12\x0b\n\x03tag\x18\x05 \x01(\t"Y\n\x10LoginCredentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x1a\n\x12\x65ncrypted_password\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\x12\x0b\n\x03tag\x18\x04 \x01(\t2\xd6\x01\n\x0bRagServices\x12I\n\x0cRegistration\x12 .ragflow.RegistrationCredentials\x1a\x17.ragflow.ResponseString\x12;\n\x05Login\x12\x19.ragflow.LoginCredentials\x1a\x17.ragflow.ResponseString\x12?\n\tGetApiKey\x12\x19.ragflow.LoginCredentials\x1a\x17.ragflow.ResponseStringb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ragflow_register_login_getapi_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RESPONSESTRING"]._serialized_start = 48
    _globals["_RESPONSESTRING"]._serialized_end = 79
    _globals["_REGISTRATIONCREDENTIALS"]._serialized_start = 81
    _globals["_REGISTRATIONCREDENTIALS"]._serialized_end = 191
    _globals["_LOGINCREDENTIALS"]._serialized_start = 193
    _globals["_LOGINCREDENTIALS"]._serialized_end = 282
    _globals["_RAGSERVICES"]._serialized_start = 285
    _globals["_RAGSERVICES"]._serialized_end = 499
# @@protoc_insertion_point(module_scope)
